//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_hoa_don
    {
        public int macthd { get; set; }
        public string ma_hd { get; set; }
        public string makho_hangchitiet { get; set; }
    
        public virtual hoa_don hoa_don { get; set; }
        public virtual khohang_hanghoa khohang_hanghoa { get; set; }
    }
}
