//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hang_hoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hang_hoa()
        {
            this.hoa_don = new HashSet<hoa_don>();
            this.khohang_hanghoa = new HashSet<khohang_hanghoa>();
        }
    
        public string ma_hang_hoa { get; set; }
        public string ten { get; set; }
        public Nullable<System.DateTime> ngay_sx { get; set; }
        public Nullable<System.DateTime> hsd { get; set; }
        public Nullable<double> gia_ban { get; set; }
        public Nullable<double> gia_nhap { get; set; }
        public string hinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoa_don> hoa_don { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<khohang_hanghoa> khohang_hanghoa { get; set; }
    }
}
