//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoa_don
    {
        public string ma_hd { get; set; }
        public string ma_kh { get; set; }
        public string ma_nv { get; set; }
        public string ma_hang_hoa { get; set; }
        public Nullable<System.DateTime> ngay_lap { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<double> thanh_tien { get; set; }
        public string trang_thai { get; set; }
    
        public virtual hang_hoa hang_hoa { get; set; }
        public virtual nhan_vien nhan_vien { get; set; }
        public virtual khach_hang khach_hang { get; set; }
    }
}
