//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1
{
    using System;
    using System.Collections.Generic;
    
    public partial class khohang_hanghoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khohang_hanghoa()
        {
            this.chi_tiet_hoa_don = new HashSet<chi_tiet_hoa_don>();
        }
    
        public string makho_hangchitiet { get; set; }
        public string ma_kho_hang { get; set; }
        public string ma_hang_hoa { get; set; }
        public Nullable<System.DateTime> ngay_nhap { get; set; }
        public Nullable<System.DateTime> ngay_xuat { get; set; }
        public Nullable<int> so_luong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_hoa_don> chi_tiet_hoa_don { get; set; }
        public virtual hang_hoa hang_hoa { get; set; }
        public virtual kho_hang kho_hang { get; set; }
    }
}
