//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1
{
    using System;
    using System.Collections.Generic;
    
    public partial class khohang_hanghoa
    {
        public string ma_kho_hang { get; set; }
        public string ma_hang_hoa { get; set; }
        public Nullable<System.DateTime> ngay_nhap { get; set; }
        public Nullable<System.DateTime> ngay_xuat { get; set; }
        public Nullable<int> so_luong { get; set; }
    
        public virtual hang_hoa hang_hoa { get; set; }
        public virtual kho_hang kho_hang { get; set; }
    }
}
